# Generated by Django 5.1.6 on 2025-02-11 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_remove_post_description_alter_comment_post"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="expiryDate",
            new_name="expiresAt",
        ),
    ]
