# Generated by Django 5.1.6 on 2025-02-11 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_rename_expirydate_post_expiresat"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comment",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="post",
            options={"ordering": ["-created_at"]},
        ),
        migrations.RenameField(
            model_name="author",
            old_name="createdAt",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="comment",
            old_name="createdAt",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="post",
            old_name="createdAt",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="post",
            old_name="expiresAt",
            new_name="expires_at",
        ),
        migrations.RenameField(
            model_name="post",
            old_name="updatedAt",
            new_name="updated_at",
        ),
        migrations.RenameField(
            model_name="tag",
            old_name="createdAt",
            new_name="created_at",
        ),
    ]
