# Generated by Django 5.1.6 on 2025-03-27 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0007_comment_author_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="author_ip",
            field=models.GenericIPAddressField(default="1.2.3.4"),
        ),
        migrations.AddField(
            model_name="comment",
            name="author_user_agent",
            field=models.CharField(default="", max_length=200),
        ),
    ]
